#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Jan 28 17:30:46 ICT 2026
maven-metadata-central.xml.lastUpdated=1681540495820
maven-metadata-nexus-repo.xml.lastUpdated=1769596246543
