#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Jan 28 16:01:12 ICT 2026
maven-metadata-maven-default-http-blocker.xml.error=Could not transfer metadata org.apache.commons\:commons-lang3/maven-metadata.xml from/to maven-default-http-blocker (http\://0.0.0.0/)\: Blocked mirror for repositories\: [maven-group (http\://10.148.108.26\:8081/repository/maven-public/, default, releases+snapshots)]
maven-metadata-central.xml.lastUpdated=1705123977510
maven-metadata-nexus-repo.xml.lastUpdated=1769590872060
maven-metadata-maven-default-http-blocker.xml/@default-maven-default-http-blocker-http\://0.0.0.0/.lastUpdated=1705124028990
